# -*- coding: utf-8 -*-
"""git intro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uYC0UwzfurNnhVLdZPKmB-3OoXGs6nsI
"""

a = 17
b = 4
c = 2000

a + b + c