# -*- coding: utf-8 -*-
"""Zoo Management

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bpBi7um6bKrOyOnyR9eKTicmjE7-O8-T
"""

from abc import ABC, abstractmethod

# Animal Class
class Animal(ABC):
  def __init__(self, name, species, age, food):
    self.name = name
    self.species = species
    self.age = age
    self.food = food

  def __str__(self):
    return f"{self.name} ({self.species}), Age: {self.age}, Food: {self.food}"

  @abstractmethod
  def make_sound(self):
    pass

  def feed(self):
    print(f"{self.name} eats {self.food}.")

# Mammal Class
class Mammal(Animal):
  def __init__(self, name, species, age, food, has_fur=True):
    super().__init__(name, species, age, food)
    self.has_fur = has_fur

  def make_sound(self):
    print(f"{self.name} roars.")

# Bird Class
class Bird(Animal):
  def __init__(self, name, species, age, food, can_fly=True):
    super().__init__(name, species, age, food)
    self.can_fly = can_fly

  def make_sound(self):
    print(f"{self.name} chirps.")

# Reptile Class
class Reptile(Animal):
    def __init__(self, name, species, age, food, has_scales = True):
        super().__init__(name, species, age, food)
        self.has_scales = has_scales

    def make_sound(self):
        print(f"{self.name} hisses.")

# Zoo Class
class Zoo:
    def __init__(self):
        self.animals = []

    def add_animal(self, animal):
        self.animals.append(animal)
        print(f"Added {animal.name} to the zoo.")

    def list_animals(self):
        if not self.animals:
            print("No animals!")
        else:
            print("Animals in the zoo:")
            for animal in self.animals:
                print(animal)

    def make_all_sounds(self):
        print("Animal sounds:")
        for animal in self.animals:
            animal.make_sound()

    def feed_all_animals(self):
        print("Feeding all animals:")
        for animal in self.animals:
            animal.feed()

def main():
  zoo = Zoo()
  lion = Mammal("Leo", "Lion", 4, "Meat", True)
  eagle = Bird("Eddie", "Eagle", 3, "Fish", True)
  snake = Reptile("Slitherine", "Snake", 2, "Mice", True)

  zoo.add_animal(lion)
  zoo.add_animal(eagle)
  zoo.add_animal(snake)

  zoo.list_animals()
  zoo.make_all_sound()
  zoo.feed_all()

if __name__ == "__main__":
  main()
